[package]
name = "uniform_distro_window"
version = "0.1.0"
authors = ["Elijah Grubb <egrubb@cs.umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

